laneband_fname:
  gelbandtable_030818_Gel1.xlsx
laneband_fldr:
  030718_Cellulases
laneband_basepath:
  C:\Users\kavandermeul\Box Sync\Data\ssEnzymeAssays
lanedescription_fname:
  Gel1_LaneDescriptions.xlsx
lanedescription_fldr:
  030718_Cellulases
lanedescription_basepath:
  C:\Users\kavandermeul\Box Sync\Data\ssEnzymeAssays




